site_name: Ashet Home Computer

site_url: https://ashet.computer/

site_description: Home page of the Ashet Home Computer.
site_author: Ashet Technologies


nav:
  - About: about.md
  - Hardware: 
    - Overview: hardware.md
    - Specs: hardware/specs.md
  - OS: ashet-os.md
  - Community & Resources: community.md

repo_url: https://github.com/Ashet-Technologies/ashet.computer/

theme: mkdocs

extra_css:
  - css/extra.css
