name: Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python just
          version: 1.0

      - name: Render Website
        run: |
          just venv
          just build

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Website
          path: render/
    
  